### ISSUE TITLE
Invalid return generation for Getter

### ISSUE THREAD

**Issue by PumpkinSeed** [infiniteloopcloud/protoc-gen-go-types#12]
When we have a type override for alias types like `type Something string` and it's generating the return of the Getter, it generates an invalid implementation.

ex.:

```
// test.proto
message Anything {
  string something = 1 [(go_type) = "Something", (go_import) = ""];
}
```

```
// test.go
type Something string
```

```
// test.pb.go

type Anything struct {
	Something Something

func (x *Anything) GetSomething() Something {
	if x != nil {
		return x.Something
	}
	return Something{}
}
```

The issue here is the `return Something{}`, because it's a string underneath.

**Comment by borosr** [comment]
I'm going to create a new field option called `zero_override`. It has a string value, where you can pass the default value what you want.
