### ISSUE TITLE
Support for custom struct tags

### ISSUE THREAD

**Issue by PumpkinSeed** [infiniteloopcloud/protoc-gen-go-types#20]
Add extension for custom struct tags. This extension must overwrite the original value of an existing struct tag, or add it if it does not exist yet.

Format should be something like:

```
string created_at = 6 [(go_struct_tags) = "json=something,omitempty;validate=date"];
```

It's important to exclude the `protobuf` tag. It MUST NOT be changed by this.

**Comment by borosr** [comment]
Okay then the go_struct_tags format rules are the following:
- tag name and value must be separated by `=` sign
- individual tags must be separated by `;` sign
